[package]
name = "websocket-codec"
description = "A Tokio codec for the websocket protocol"
version = "0.5.2"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "../README.md"

[dependencies]
base64 = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
httparse = { workspace = true }
rand = { workspace = true }
sha1 = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }

[dev-dependencies]
assert-allocations = { workspace = true }
clap = { workspace = true }
criterion = { workspace = true }
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
static_assertions = { workspace = true }

[[bench]]
name = "bench"
harness = false
