[workspace]
resolver = "3"
members = [
    "assert-allocations",
    "fuzz",
    "hyper-websocket-lite",
    "websocket-codec",
    "websocket-lite"
]

[workspace.package]
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/1tgr/rust-websocket-lite"

[workspace.dependencies]
assert-allocations = { path = "assert-allocations" }
base64 = "0.23"
byteorder = "1"
bytes = "1"
clap = { version = "4", features = ["derive"] }
criterion = "0.8"
futures-util = { version = "0.3", default-features = false }
http-body-util = "0.1"
httparse = "1"
hyper = "1"
hyper-util = "0.1"
native-tls = "0.2"
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.10"
rustls = { version = "0.23", default-features = false, features = ["logging", "std", "tls12"] }
rustls-native-certs = "0.8"
sha1 = { version = "0.11", default-features = false }
static_assertions = "1"
tokio = { version = "1", default-features = false }
tokio-native-tls = "0.3"
tokio-rustls = { version = "0.26", default-features = false, features = ["logging", "tls12"] }
tokio-util = { version = "0.7", default-features = false }
url = "2"
webpki-roots = "1"
websocket-codec = { version = "0.5", path = "websocket-codec" }

[profile.bench]
debug = true

[profile.release]
debug = true
