[package]
name = "websocket-lite"
description = "A fast, low-overhead WebSocket client"
version = "0.5.2"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "../README.md"

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
native-tls = { workspace = true, optional = true }
rand = { workspace = true }
rustls = { workspace = true, optional = true }
rustls-native-certs = { workspace = true, optional = true }
tokio = { workspace = true, features = ["net", "io-util"] }
tokio-native-tls = { workspace = true, optional = true }
tokio-rustls = { workspace = true, optional = true }
tokio-util = { workspace = true, features = ["codec"] }
url = { workspace = true }
webpki-roots = { workspace = true, optional = true }
websocket-codec = { workspace = true }

[dev-dependencies]
clap = { workspace = true }
futures-util = { workspace = true, features = ["sink", "std"] }
tokio = { workspace = true, features = ["macros", "time", "io-std", "rt-multi-thread"] }

[features]
default = ["ssl-native-tls"]
__ssl = []
ssl-native-tls = ["__ssl", "dep:native-tls", "dep:tokio-native-tls"]
__ssl-rustls = ["__ssl", "dep:rustls", "dep:tokio-rustls"]
ssl-rustls-webpki-roots = ["__ssl-rustls", "dep:webpki-roots"]
ssl-rustls-native-roots = ["__ssl-rustls", "dep:rustls-native-certs"]
